//
//  EmiCalculatorModels.swift
//  EmiCalculator
//
//  Created by Tirupati Balan on 11/04/16.
//  Copyright (c) 2016 CelerStudio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct EmiCalculatorRequest
{
    struct RequestEmiCalculation {
        var loanAmount : Double
        var loanTenure : NSInteger
        var interestRate : Double
    }
    var requestEmiCalculation : RequestEmiCalculation
}

struct EmiCalculatorResponse
{
    struct ResponseEmiCalculation {
        var totalPayment : Double
        var totalPaymentInterest : Double
        var loanEmi : Double
    }
    var responseEmiCalculation : ResponseEmiCalculation
}

struct EmiCalculatorViewModel
{
    struct DisplayEmiCalculation {
        var totalPayment : Double
        var totalPaymentInterest : Double
        var loanEmi : Double
    }
    var emiCalculation : DisplayEmiCalculation
}
