//
//  EmiCalculatorViewController.swift
//  EmiCalculator
//
//  Created by Tirupati Balan on 11/04/16.
//  Copyright (c) 2016 CelerStudio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol EmiCalculatorViewControllerInput
{
  func displaySomething(viewModel: EmiCalculatorViewModel)
}

protocol EmiCalculatorViewControllerOutput
{
  func doSomething(request: EmiCalculatorRequest)
}

class EmiCalculatorViewController: UIViewController, EmiCalculatorViewControllerInput
{
  var output: EmiCalculatorViewControllerOutput!
  var router: EmiCalculatorRouter!
  
  // MARK: Object lifecycle
  
  override func awakeFromNib()
  {
    super.awakeFromNib()
    EmiCalculatorConfigurator.sharedInstance.configure(self)
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomethingOnLoad()
  }
  
  // MARK: Event handling
  
  func doSomethingOnLoad()
  {
    // NOTE: Ask the Interactor to do some work
    
    let request = EmiCalculatorRequest()
    output.doSomething(request)
  }
  
  // MARK: Display logic
  
  func displaySomething(viewModel: EmiCalculatorViewModel)
  {
    // NOTE: Display the result from the Presenter
    
    // nameTextField.text = viewModel.name
  }
}
