//
//  EmiCalculatorPresenter.swift
//  EmiCalculator
//
//  Created by Tirupati Balan on 11/04/16.
//  Copyright (c) 2016 CelerStudio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol EmiCalculatorPresenterInput
{
  func presentSomething(response: EmiCalculatorResponse)
}

protocol EmiCalculatorPresenterOutput: class
{
  func displaySomething(viewModel: EmiCalculatorViewModel)
}

class EmiCalculatorPresenter: EmiCalculatorPresenterInput
{
  weak var output: EmiCalculatorPresenterOutput!
  
  // MARK: Presentation logic
  
  func presentSomething(response: EmiCalculatorResponse)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = EmiCalculatorViewModel()
    output.displaySomething(viewModel)
  }
}
